version: "3.9"

services:

    database_brainny:
        image: postgres
        container_name: database_brainny
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/data/postgres

  
    # api:
    #         image: .
            
    #         container_name: brainnyDoctor_api
            
    #         restart: always
            
    #         ports:
    #             - 3000:3000

    #         volumes: 
    #         - .:/usr/app
    #         links: 
    #         - database_brainny
    #         depends_on:
    #         - database_brainny               



volumes:
    pgdata:
        driver: local
